### dictionary basics

source: https://www.youtube.com/watch?v=zmdjNSmRXF4&list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS&index=2

In [2]:
# define dictionary
person = {
    "first":"Stutie",
    "last":"Banerjie",
    "email":"test@gmail.com"
}

In [3]:
# make dictionary into list (w/ one person)
people = {
    "first":["Stutie"],
    "last":["Banerjie"],
    "email":["test@gmail.com"]
}

In [4]:
# add people to list
people = {
    "first":["Stutie", "Jane", "Shane"],
    "last":["Banerjie", "Doe", "Hollander"],
    "email":["test@gmail.com", "JaneDoe@email.com", "hockey@gmail.com"]
}

In [5]:
# access email column of dictionary
people["email"]

['test@gmail.com', 'JaneDoe@email.com', 'hockey@gmail.com']

### data frame basics

In [6]:
# create dataframe from dictionary
import pandas as pd

df = pd.DataFrame(people)

df

    first       last              email
0  Stutie   Banerjie     test@gmail.com
1    Jane        Doe  JaneDoe@email.com
2   Shane  Hollander   hockey@gmail.com

In [7]:
# access single column of dataframe(more consistent)
df['email']
# outprints same way
df.email

0       test@gmail.com
1    JaneDoe@email.com
2     hockey@gmail.com
Name: email, dtype: str

In [8]:
# data frame column is a series
type(df['email'])

# dataframe - rows & columns; container of multiple series
# series - rows of a single column

pandas.Series

In [9]:
# access multiple columns of a dataframe
df[['last', 'email']]

        last              email
0   Banerjie     test@gmail.com
1        Doe  JaneDoe@email.com
2  Hollander   hockey@gmail.com

In [10]:
# access rows by integer location
df.iloc[0] # first row

first            Stutie
last           Banerjie
email    test@gmail.com
Name: 0, dtype: str

In [11]:
df.iloc[[0,1]] # first 2 rows

    first      last              email
0  Stutie  Banerjie     test@gmail.com
1    Jane       Doe  JaneDoe@email.com

In [12]:
# specify columns to show
df.iloc[[0,1],2] # emails for first 2 rows

0       test@gmail.com
1    JaneDoe@email.com
Name: email, dtype: str

In [13]:
df

    first       last              email
0  Stutie   Banerjie     test@gmail.com
1    Jane        Doe  JaneDoe@email.com
2   Shane  Hollander   hockey@gmail.com

In [14]:
# row associated with index 0
df.loc[0]

first            Stutie
last           Banerjie
email    test@gmail.com
Name: 0, dtype: str

In [15]:
# row associated with index 0 and 1
df.loc[[0,1]]

    first      last              email
0  Stutie  Banerjie     test@gmail.com
1    Jane       Doe  JaneDoe@email.com

In [17]:
# specify columns to show
df.loc[[0,1],['email','last']]

               email      last
0     test@gmail.com  Banerjie
1  JaneDoe@email.com       Doe